DROP TABLE "ACTIWEB"."REGION" cascade constraints;
DROP TABLE "ACTIWEB"."COUNTRY" cascade constraints;
DROP TABLE "ACTIWEB"."LOCATION" cascade constraints;
DROP TABLE "ACTIWEB"."JOB_HISTORY" cascade constraints;
DROP TABLE "ACTIWEB"."DEPARTMENT" cascade constraints;
DROP TABLE "ACTIWEB"."EMPLOYEE" cascade constraints;
DROP TABLE "ACTIWEB"."JOB" cascade constraints;

CREATE TABLE "ACTIWEB"."REGION" 
(	"REGION_ID" NUMBER, 
"REGION_NAME" VARCHAR2(25 BYTE)
);

CREATE TABLE "ACTIWEB"."COUNTRY" 
(	"COUNTRY_ID" CHAR(2 BYTE), 
"COUNTRY_NAME" VARCHAR2(40 BYTE), 
"REGION_ID" NUMBER
);

CREATE TABLE "ACTIWEB"."LOCATION" 
(	"LOCATION_ID" NUMBER(4,0), 
"STREET_ADDRESS" VARCHAR2(40 BYTE), 
"POSTAL_CODE" VARCHAR2(12 BYTE), 
"CITY" VARCHAR2(30 BYTE), 
"STATE_PROVINCE" VARCHAR2(25 BYTE), 
"COUNTRY_ID" CHAR(2 BYTE)
);

CREATE TABLE "ACTIWEB"."DEPARTMENT" 
(	"DEPARTMENT_ID" NUMBER(4,0), 
"DEPARTMENT_NAME" VARCHAR2(30 BYTE), 
"LOCATION_ID" NUMBER(4,0)
);

CREATE TABLE "ACTIWEB"."EMPLOYEE" 
(	"EMPLOYEE_ID" NUMBER(6,0), 
"FIRST_NAME" VARCHAR2(20 BYTE), 
"LAST_NAME" VARCHAR2(25 BYTE), 
"EMAIL" VARCHAR2(25 BYTE), 
"PHONE_NUMBER" VARCHAR2(20 BYTE), 
"HIRE_DATE" DATE, 
"JOB_ID" VARCHAR2(10 BYTE), 
"SALARY" NUMBER(8,2), 
"COMMISSION_PCT" NUMBER(2,2), 
"MANAGER_ID" NUMBER(6,0), 
"DEPARTMENT_ID" NUMBER(4,0)
) ;
CREATE TABLE "ACTIWEB"."JOB" 
(	"JOB_ID" VARCHAR2(10 BYTE), 
"JOB_TITLE" VARCHAR2(35 BYTE), 
"MIN_SALARY" NUMBER(6,0), 
"MAX_SALARY" NUMBER(6,0)
);

CREATE TABLE "ACTIWEB"."JOB_HISTORY" 
(	"EMPLOYEE_ID" NUMBER(6,0), 
"START_DATE" DATE, 
"END_DATE" DATE, 
"JOB_ID" VARCHAR2(10 BYTE), 
"DEPARTMENT_ID" NUMBER(4,0)
);

ALTER TABLE "ACTIWEB"."REGION" ADD CONSTRAINT "REG_ID_PK" PRIMARY KEY ("REGION_ID");
ALTER TABLE "ACTIWEB"."COUNTRY" ADD CONSTRAINT "COUNTRY_C_ID_PK" PRIMARY KEY ("COUNTRY_ID");
ALTER TABLE "ACTIWEB"."LOCATION" ADD CONSTRAINT "LOC_ID_PK" PRIMARY KEY ("LOCATION_ID");
ALTER TABLE "ACTIWEB"."DEPARTMENT" ADD CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID");
ALTER TABLE "ACTIWEB"."EMPLOYEE" ADD CONSTRAINT "EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID");
ALTER TABLE "ACTIWEB"."JOB" ADD CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID");

ALTER TABLE "ACTIWEB"."REGION" MODIFY ("REGION_ID" CONSTRAINT "REGION_ID_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."COUNTRY" MODIFY ("COUNTRY_ID" CONSTRAINT "COUNTRY_ID_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."COUNTRY" ADD CONSTRAINT "COUNTR_REG_FK" FOREIGN KEY ("REGION_ID")
REFERENCES "ACTIWEB"."REGION" ("REGION_ID") ENABLE;

CREATE INDEX "ACTIWEB"."LOC_CITY_IX" ON "ACTIWEB"."LOCATION" ("CITY") ;
CREATE INDEX "ACTIWEB"."LOC_STATE_PROVINCE_IX" ON "ACTIWEB"."LOCATION" ("STATE_PROVINCE") ;
CREATE INDEX "ACTIWEB"."LOC_COUNTRY_IX" ON "ACTIWEB"."LOCATION" ("COUNTRY_ID") ;
ALTER TABLE "ACTIWEB"."LOCATION" MODIFY ("CITY" CONSTRAINT "LOC_CITY_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."LOCATION" ADD CONSTRAINT "LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_ID")
REFERENCES "ACTIWEB"."COUNTRY" ("COUNTRY_ID") ENABLE;
ALTER TABLE "ACTIWEB"."EMPLOYEE" ADD CONSTRAINT "EMP_SALARY_MIN" CHECK (salary > 0) ENABLE;
ALTER TABLE "ACTIWEB"."EMPLOYEE" MODIFY ("JOB_ID" CONSTRAINT "EMP_JOB_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."EMPLOYEE" MODIFY ("HIRE_DATE" CONSTRAINT "EMP_HIRE_DATE_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."EMPLOYEE" MODIFY ("EMAIL" CONSTRAINT "EMP_EMAIL_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."EMPLOYEE" MODIFY ("LAST_NAME" CONSTRAINT "EMP_LAST_NAME_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."EMPLOYEE" ADD CONSTRAINT "EMP_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID")
REFERENCES "ACTIWEB"."DEPARTMENT" ("DEPARTMENT_ID") ENABLE;
ALTER TABLE "ACTIWEB"."EMPLOYEE" ADD CONSTRAINT "EMP_JOB_FK" FOREIGN KEY ("JOB_ID")
REFERENCES "ACTIWEB"."JOB" ("JOB_ID") ENABLE;

CREATE UNIQUE INDEX "ACTIWEB"."EMP_EMAIL_UK" ON "ACTIWEB"."EMPLOYEE" ("EMAIL") ;

CREATE INDEX "ACTIWEB"."EMP_DEPARTMENT_IX" ON "ACTIWEB"."EMPLOYEE" ("DEPARTMENT_ID") ;
CREATE INDEX "ACTIWEB"."EMP_JOB_IX" ON "ACTIWEB"."EMPLOYEE" ("JOB_ID") ;
CREATE INDEX "ACTIWEB"."EMP_MANAGER_IX" ON "ACTIWEB"."EMPLOYEE" ("MANAGER_ID") ;
CREATE INDEX "ACTIWEB"."EMP_NAME_IX" ON "ACTIWEB"."EMPLOYEE" ("LAST_NAME", "FIRST_NAME") ;

CREATE INDEX "ACTIWEB"."DEPT_LOCATION_IX" ON "ACTIWEB"."DEPARTMENT" ("LOCATION_ID") ;

ALTER TABLE "ACTIWEB"."DEPARTMENT" MODIFY ("DEPARTMENT_NAME" CONSTRAINT "DEPT_NAME_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."DEPARTMENT" ADD CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID")
REFERENCES "ACTIWEB"."LOCATION" ("LOCATION_ID") ENABLE;

ALTER TABLE "ACTIWEB"."JOB" MODIFY ("JOB_TITLE" CONSTRAINT "JOB_TITLE_NN" NOT NULL ENABLE);

CREATE UNIQUE INDEX "ACTIWEB"."JHIST_EMP_ID_ST_DATE_PK" ON "ACTIWEB"."JOB_HISTORY" ("EMPLOYEE_ID", "START_DATE") 
CREATE INDEX "ACTIWEB"."JHIST_JOB_IX" ON "ACTIWEB"."JOB_HISTORY" ("JOB_ID") ;
CREATE INDEX "ACTIWEB"."JHIST_EMPLOYEE_IX" ON "ACTIWEB"."JOB_HISTORY" ("EMPLOYEE_ID") ;
CREATE INDEX "ACTIWEB"."JHIST_DEPARTMENT_IX" ON "ACTIWEB"."JOB_HISTORY" ("DEPARTMENT_ID") ;
ALTER TABLE "ACTIWEB"."JOB_HISTORY" ADD CONSTRAINT "JHIST_EMP_ID_ST_DATE_PK" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE")
ALTER TABLE "ACTIWEB"."JOB_HISTORY" ADD CONSTRAINT "JHIST_DATE_INTERVAL" CHECK (end_date > start_date) ENABLE;
ALTER TABLE "ACTIWEB"."JOB_HISTORY" MODIFY ("JOB_ID" CONSTRAINT "JHIST_JOB_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."JOB_HISTORY" MODIFY ("END_DATE" CONSTRAINT "JHIST_END_DATE_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."JOB_HISTORY" MODIFY ("START_DATE" CONSTRAINT "JHIST_START_DATE_NN" NOT NULL ENABLE);
ALTER TABLE "ACTIWEB"."JOB_HISTORY" MODIFY ("EMPLOYEE_ID" CONSTRAINT "JHIST_EMPLOYEE_NN" NOT NULL ENABLE);

ALTER TABLE "ACTIWEB"."JOB_HISTORY" ADD CONSTRAINT "JHIST_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID")
REFERENCES "ACTIWEB"."DEPARTMENT" ("DEPARTMENT_ID") ENABLE;
ALTER TABLE "ACTIWEB"."JOB_HISTORY" ADD CONSTRAINT "JHIST_EMP_FK" FOREIGN KEY ("EMPLOYEE_ID")
REFERENCES "ACTIWEB"."EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
ALTER TABLE "ACTIWEB"."JOB_HISTORY" ADD CONSTRAINT "JHIST_JOB_FK" FOREIGN KEY ("JOB_ID")
REFERENCES "ACTIWEB"."JOB" ("JOB_ID") ENABLE;
